echo "en_us"
## main.sh
o_1="$O Correct running directory."
o_2="$O will check for updates this time."
o_3="$O versions are consistent."
o_4="$O preparation is successful, running the main body..."
o_5="$O Each build folder has the same version."
o_6="$O This time, all compiled files will be updated to the latest version."
o_7="$O This time, all compiled files will be updated to the specified version."
w_1="$W is not a recommended running directory, please move it to the same level as $directory_main or other directories."
w_2="$W is located in an unknown run directory, but the run directory is empty."
w_3="$W versions of each compilation folder are inconsistent."
w_4="$W Maximum difference in version numbers:"
w_5="$W is not a recommended running directory, please move it to the same level as $directory_main or other directories."
w_6="$W $0 $1 : ${1}=md but ${3}=?"
e_1="$E Wrong parameter, enter $0 ${ap_help} for help."
e_2="$E This directory is not an empty directory (except ${file_name} and the generated data files)"
e_3="$E Exit..."
e_4="$E "
read_1="Download the compiled files to this directory? [Y/n]:"
read_2="Download the latest $file_name? [Y/n]:"
read_3="Next step? [Ignore N/Update to the latest UL/Update to the specified version US]:" ## neglect/Updated to the latest/Update to specified version
read_4="Input [${ap3_update_1}/${ap3_update_2} | Default is ${ap3_update_1}]:"
read_5="Type the page to jump to[1]:"
read_6="KEY [Get help:$0 ${ap_help}]"
Server_sh_read_1="Type server folder name [server]:"
tip_1="Start downloading..."
tip_2="The versions are inconsistent."
tip_3="Skip updates."
help_title="HELP"
h_c="Directory"
h_c_1="Added value help page --- 1"
h_c_2="KEY help page --- 2"
h_1_1="1. $0 ${ap_help} - Get help"
h_1_2="2. $0 ${ap_update} empty=${file_name}/${ap2_update} ${ap3_update_1}/${ap3_update_2} - Update (need to add parameters later)"
h_1_2_1="   ${file_name}/no input - check for update $file_name"
h_1_2_2="   ${ap2_update} - update the compilation folder (need to add parameters later)"
h_1_2_2_1="      ${ap3_update_1} - Update to the latest version"
h_1_2_2_2="      ${ap3_update_2} - Update to the specified version"
h_2_1="1. t1 - Test compilation ${client_name}"
h_2_2="2. t2 - Test compilation ${editor_name}"
h_2_3="3. t3 - Test compilation ${server_name}"
h_2_4="4. t4 - Test compilation ALL"