echo "zh_tw"
## main.sh
o_1="$O 正確的運行目錄。"
o_2="$O 本次將檢查更新。"
o_3="$O 版本一致。"
o_4="$O 準備成功，運行主體..."
o_5="$O 每個編譯文件夾版本相同。"
o_6="$O 本次將所有編譯文件更新至最新版本。"
o_7="$O 本次將所有編譯文件更新至指定版本。"
w_1="$W 不建議的運行目錄，請將其移至 $directory_main 等目錄同級。"
w_2="$W 位於未知運行目錄，但運行目錄為空。"
w_3="$W 各個編譯文件夾版本不一致。"
w_4="$W 版本號最大相差:"
w_5="$W 不建議的運行目錄，請將其移至 $directory_main 等目錄同級。"
w_6="$W $0 $1 : ${1}=md 但是${3}=?"
e_1="$E 錯誤的參數，輸入$0 ${ap_help}獲取幫助。"
e_2="$E 該目錄不是空目錄(${file_name}及產生的數據文件除外)"
e_3="$E 退出..."
e_4="$E "
read_1="下載編譯文件至此目錄? [Y/n]:"
read_2="下載最新的 $file_name ? [Y/n]:"
read_3="下一步執行? [忽略N/更新至最新UL/更新至指定版本US]:" ## neglect/Updated to the latest/Update to specified version
read_4="輸入[${ap3_update_1}/${ap3_update_2} | 默認為${ap3_update_1}]:"
read_5="鍵入跳轉到的頁面[1]:"
read_6="KEY [獲取幫助:$0 ${ap_help}]"
read_7="选择指定版本号[tag]:"
tip_1="開始下載..."
tip_2="版本不一致。"
tip_3="跳過更新。"
help_title="HELP"
h_c="目錄"
h_c_1="附加值幫助頁面 --- 1"
h_c_2="KEY幫助頁面 --- 2"
h_1_1="1. $0 ${ap_help} - 獲取幫助"
h_1_2="2. $0 ${ap_update} 空=${file_name}/${ap2_update} ${ap3_update_1}/${ap3_update_2} - 更新 (後需加參)"
h_1_2_1="   ${file_name}/不輸入 - 檢查更新$file_name"
h_1_2_2="   ${ap2_update} - 更新編譯文件夾 (後需加參)"
h_1_2_2_1="      ${ap3_update_1} - 更新至最新版本"
h_1_2_2_2="      ${ap3_update_2} - 更新至指定版本"
h_2_1="1. t1 - 測試編譯${client_name}"
h_2_2="2. t2 - 測試編譯${editor_name}"
h_2_3="3. t3 - 測試編譯${server_name}"
h_2_4="4. t4 - 測試編譯ALL"