echo "zh_cn"
## main.sh
o_1="$O 正确的运行目录。"
o_2="$O 本次将检查更新。"
o_3="$O 版本一致。"
o_4="$O 准备成功，运行主体..."
o_5="$O 每个编译文件夹版本相同。"
o_6="$O 本次将所有编译文件更新至最新版本。"
o_7="$O 本次将所有编译文件更新至指定版本。"
w_1="$W 不建议的运行目录，请将其移至 $directory_main 等目录同级。"
w_2="$W 位于未知运行目录，但运行目录为空。"
w_3="$W 各个编译文件夹版本不一致。"
w_4="$W 版本号最大相差:"
w_5="$W 不建议的运行目录，请将其移至 $directory_main 等目录同级。"
w_6="$W $0 $1 : ${1}=md 但是${3}=?"
e_1="$E 错误的参数，输入$0 ${ap_help}获取帮助。"
e_2="$E 该目录不是空目录(${file_name}及产生的数据文件除外)"
e_3="$E 退出..."
e_4="$E "
read_1="下载编译文件至此目录? [Y/n]:"
read_2="下载最新的 $file_name ? [Y/n]:"
read_3="下一步执行? [忽略N/更新至最新UL/更新至指定版本US]:" ## neglect/Updated to the latest/Update to specified version
read_4="输入[${ap3_update_1}/${ap3_update_2} | 默认为${ap3_update_1}]:"
read_5="键入跳转到的页面[1]:"
read_6="KEY [获取帮助:$0 ${ap_help}]"
Server_sh_read_1="键入服务器文件夹名称[server]:"
tip_1="开始下载..."
tip_2="版本不一致。"
tip_3="跳过更新。"
help_title="HELP"
h_c="目录"
h_c_1="附加值帮助页面 --- 1"
h_c_2="KEY帮助页面 --- 2"
h_1_1="1. $0 ${ap_help} - 获取帮助"
h_1_2="2. $0 ${ap_update} 空=${file_name}/${ap2_update} ${ap3_update_1}/${ap3_update_2} - 更新 (后需加参)"
h_1_2_1="   ${file_name}/不输入 - 检查更新$file_name"
h_1_2_2="   ${ap2_update} - 更新编译文件夹 (后需加参)"
h_1_2_2_1="      ${ap3_update_1} - 更新至最新版本"
h_1_2_2_2="      ${ap3_update_2} - 更新至指定版本"
h_2_1="1. t1 - 测试编译${client_name}"
h_2_2="2. t2 - 测试编译${editor_name}"
h_2_3="3. t3 - 测试编译${server_name}"
h_2_4="4. t4 - 测试编译ALL"